### PR TITLE
Don't case-fold paths when using table syntax

### LINKED ISSUE #239: Tests fail on case-sensitive systems if path has upper-case characters
```
n@emeritus:~/Documents/stackable/trino-storage$ mvn test
[snip]
java.io.UncheckedIOException: Failed to open stream for file:/home/n/documents/stackable/trino-storage/target/test-classes/example-data/numbers-2.csv
        at org.ebyhr.trino.storage.StorageClient.getInputStream(StorageClient.java:115)
        at org.ebyhr.trino.storage.StorageClient.lambda$getTable$0(StorageClient.java:84)
        at org.ebyhr.trino.storage.operator.CsvPlugin.getFields(CsvPlugin.java:41)
        at org.ebyhr.trino.storage.StorageClient.getTable(StorageClient.java:84)
        at org.ebyhr.trino.storage.StorageMetadata.getStorageTableMetadata(StorageMetadata.java:165)
        at org.ebyhr.trino.storage.StorageMetadata.getTableMetadata(StorageMetadata.java:88)
[snip]
n@emeritus:~/Documents/stackable/trino-storage$ cat /home/n/documents/stackable/trino-storage/target/test-classes/example-data/numbers-2.csv
cat: /home/n/documents/stackable/trino-storage/target/test-classes/example-data/numbers-2.csv: No such file or directory
n@emeritus:~/Documents/stackable/trino-storage$ cat /home/n/Documents/stackable/trino-storage/target/test-classes/example-data/numbers-2.csv
ten, 10
eleven, 11
twelve, 12
```

### PR DESCRIPTION
**Pull request by nightkr**
Fixes #239

### CODE REVIEW

**Review by nineinchnick — COMMENTED** [review]
Just a few nitpicks to make the code easier to read.

File: src/main/java/org/ebyhr/trino/storage/StorageMetadata.java [hunk 1]
```diff
@@ -167,15 +154,69 @@ private ConnectorTableMetadata getStorageTableMetadata(ConnectorSession session,
...
     }
 
-    private List<SchemaTableName> listTables(ConnectorSession session, SchemaTablePrefix prefix)
+    private List<SchemaTablePair> listTables(ConnectorSession session, SchemaTablePrefix prefix)
     {
         if (prefix.getSchema().isPresent() && prefix.getTable().isPresent()) {
-            return List.of(new SchemaTableName(prefix.getSchema().get(), prefix.getTable().get()));
+            return List.of(new SchemaTablePair(prefix.getSchema().get(), prefix.getTable().get()));
+        }
+        return listTablesImpl(session, prefix.getSchema(), Function.identity());
```
[the remark this answers is not in the document]
Comment (nightkr) [reply src/main/java/org/ebyhr/trino/storage/StorageMetadata.java:200]: I think it would make sense to have `listTablesImpl` return a `Stream`, but we can't inline it since the Trino API expects it to return a `List<SchemaTableName>`.

File: src/main/java/org/ebyhr/trino/storage/StorageMetadata.java [hunk 2]
```diff
@@ -167,15 +154,69 @@ private ConnectorTableMetadata getStorageTableMetadata(ConnectorSession session,
...
         }
 
-        return new ConnectorTableMetadata(tableName, table.getColumnsMetadata());
+        return new ConnectorTableMetadata(tableName.toSchemaTableName(), table.getColumnsMetadata());
+    }
+
+    /**
+     * Simplified variant of {@link SchemaTableName} that doesn't case-fold.
+     */
+    private static class SchemaTablePair
```
[the remark this answers is not in the document]
Comment (nightkr) [reply src/main/java/org/ebyhr/trino/storage/StorageMetadata.java:163]: Name: That's fair, the intention here was to communicate "always use this instead of `SchemaTableName`, except as required to communicate with the Trino API", rather than focus on the current difference.

Record: Sure, didn't want to use it since I couldn't see any current usage of it and wasn't sure about how it'd interact with whatever JRE compatibility policy you have.

[the remark this answers is not in the document]
Comment (nightkr) [reply src/main/java/org/ebyhr/trino/storage/StorageMetadata.java]: Record: 4e734af4ba445f60b84650f11ba4a22476167aa5

File: src/main/java/org/ebyhr/trino/storage/StorageMetadata.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (nightkr) [reply src/main/java/org/ebyhr/trino/storage/StorageMetadata.java:181]: Unless you mean inline into `listTables(ConnectorSession, SchemaTablePrefix)`?

[the remark this answers is not in the document]
Comment (nineinchnick) [reply src/main/java/org/ebyhr/trino/storage/StorageMetadata.java:181]: Yes

File: src/main/java/org/ebyhr/trino/storage/StorageMetadata.java [hunk 3]
```diff
@@ -83,29 +84,15 @@ public StorageTableHandle getTableHandle(ConnectorSession session, SchemaTableNa
...
-        }
-
-        ImmutableList.Builder<SchemaTableName> builder = ImmutableList.builder();
-        for (String schemaName : schemaNames) {
-            for (String tableName : storageClient.getTableNames(schemaName)) {
-                builder.add(new SchemaTableName(schemaName, tableName));
-            }
-        }
-        return builder.build();
+        return listTablesImpl(session, schemaNameOrNull, pair -> pair.toSchemaTableName());
```
[the remark this answers is not in the document]
Comment (nightkr) [reply src/main/java/org/ebyhr/trino/storage/StorageMetadata.java]: b017835cc19404a158b759f4f9eaadfe3fbc3f5d

File: src/main/java/org/ebyhr/trino/storage/StorageMetadata.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (nightkr) [reply src/main/java/org/ebyhr/trino/storage/StorageMetadata.java]: df2bdebd72878bed0e008025db591f304d3548f9

File: src/main/java/org/ebyhr/trino/storage/StorageMetadata.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (nightkr) [reply src/main/java/org/ebyhr/trino/storage/StorageMetadata.java]: Name: e8a9a139ac2220edfdce7df6c7ca600a77573440

**Review by nineinchnick — APPROVED** [review]
Looks great now, thanks! @ebyhr would you like to take a look?

File: src/main/java/org/ebyhr/trino/storage/StorageMetadata.java [hunk 4]
```diff
@@ -83,29 +83,18 @@ public StorageTableHandle getTableHandle(ConnectorSession session, SchemaTableNa
...
-        for (String schemaName : schemaNames) {
-            for (String tableName : storageClient.getTableNames(schemaName)) {
-                builder.add(new SchemaTableName(schemaName, tableName));
-            }
-        }
-        return builder.build();
+        SchemaTablePrefix prefix = schemaNameOrNull
+                .map(SchemaTablePrefix::new)
+                .orElseGet(SchemaTablePrefix::new);
+        return listTables(session, prefix).map(pair -> pair.toSchemaTableName()).collect(toImmutableList());
```
Comment (ebyhr) [inline src/main/java/org/ebyhr/trino/storage/StorageMetadata.java:97]: Replace lambda with method reference.

File: src/main/java/org/ebyhr/trino/storage/StorageMetadata.java [hunk 5]
```diff
@@ -144,38 +133,61 @@ public Map<SchemaTableName, List<ColumnMetadata>> listTableColumns(ConnectorSess
...
 
-        return new ConnectorTableMetadata(tableName, table.getColumnsMetadata());
+        return new ConnectorTableMetadata(tableName.toSchemaTableName(), table.getColumnsMetadata());
     }
 
-    private List<SchemaTableName> listTables(ConnectorSession session, SchemaTablePrefix prefix)
+    /**
+     * Simplified variant of {@link SchemaTableName} that doesn't case-fold.
+     */
+    private static record CaseSensitiveSchemaTableName(String schemaName, String tableName)
```
Comment (ebyhr) [inline src/main/java/org/ebyhr/trino/storage/StorageMetadata.java:165]: Rename to `RemoteTableName`. 
Also, remove the redundant `static` modifier and move this record to the bottom of the class.

File: src/main/java/org/ebyhr/trino/storage/StorageMetadata.java [hunk 6]
```diff
@@ -144,38 +133,61 @@ public Map<SchemaTableName, List<ColumnMetadata>> listTableColumns(ConnectorSess
...
+    {
+        /**
+         * Convert to {@link SchemaTableName}
+         *
+         * NOTE: This will case-fold the schema- and table names, so they may no longer be possible to resolve afterwards.
+         */
```
Comment (ebyhr) [inline src/main/java/org/ebyhr/trino/storage/StorageMetadata.java:171]: Remove unhelpful javadoc. SchemaTableName is known as returning lowercase identifiers.

File: src/main/java/org/ebyhr/trino/storage/StorageMetadata.java [hunk 7]
```diff
@@ -144,38 +133,61 @@ public Map<SchemaTableName, List<ColumnMetadata>> listTableColumns(ConnectorSess
...
+        public SchemaTableName toSchemaTableName()
+        {
+            return new SchemaTableName(schemaName(), tableName());
+        }
+    }
+
+    private Stream<CaseSensitiveSchemaTableName> listTables(ConnectorSession session, SchemaTablePrefix prefix)
```
Comment (ebyhr) [inline src/main/java/org/ebyhr/trino/storage/StorageMetadata.java:178]: Remove unused `ConnectorSession session` argument.

**Review by ebyhr — APPROVED** [review]
Please squash commits into one.

File: src/main/java/org/ebyhr/trino/storage/StorageMetadata.java (hunk 6 above)
Comment (soenkeliebau) [reply src/main/java/org/ebyhr/trino/storage/StorageMetadata.java:171]: I didn't know ... 

If the comment may be helpful to some people I'd say it does have value and could stay. 

It does explain an implementation detail that otherwise would need to be lookup up somewhere else, so is not a "increase var by 1" type of comment..

Comment (nightkr) [reply src/main/java/org/ebyhr/trino/storage/StorageMetadata.java:171]: I'd call it surprising misbehaviour but sure, it's your project, your call.

File: src/main/java/org/ebyhr/trino/storage/StorageMetadata.java (hunk 7 above)
Comment (nightkr) [reply src/main/java/org/ebyhr/trino/storage/StorageMetadata.java]: 4cb6e2469afc48e62ef4192dda20cde75ef61dea

File: src/main/java/org/ebyhr/trino/storage/StorageMetadata.java (hunk 4 above)
Comment (nightkr) [reply src/main/java/org/ebyhr/trino/storage/StorageMetadata.java]: aaedea77afbad1d373946c201c853c2bef39a94d

File: src/main/java/org/ebyhr/trino/storage/StorageMetadata.java (hunk 5 above)
Comment (nightkr) [reply src/main/java/org/ebyhr/trino/storage/StorageMetadata.java]: 300123e822625e2cec3e4493063aaf081b3d0d6d

**Comment by nightkr** [comment]
I'd call squashing a merge-time antipattern, but sure, 246600b75f81248ddba6c99ff668ba9b057d0e3c. Preserved the actual history as https://github.com/stackabletech/trino-storage/tree/bugfix/case-sensitive-table-syntax-/history.
